type Note {
  text: String!
}

type Comment {
  comment: String!
  author: String!
  list: List!
  comments: [SubComment!]! @relation
}

type SubComment {
  comment: String!
  author: String!
  parent: Comment!
}

type List {
  title: String!
  slug: String!
  comments: [Comment!] @relation
}

type Query {
  allNotes: [Note!]!
  allComments: [Comment!]
  allLists: [List!]
}
